# statsd.net configuration file.
# For help on configuring this file, please see https://github.com/lukevenediger/statsd.net/wiki/Statsd.net-Configuration-File

[general]
name = "statsd"

[listeners]
  [listeners.udp]
  enabled = true
  port = 12000

[backends]
  [backends.graphite]
  enabled = true
  host = "graphite"
  port = 2003

  [backends.console]
  enabled = true

[calc]
flushIntervalSeconds = 10
gaugesNamespace = "gauges"
countersNamespace = "counts"
setsNamespace = "sets"
timersNamespace = "timers"
removeZeroGauges = true

  [calc.percentiles.p90-5min]
  flushIntervalSeconds = 30
  percentile = 90

  [calc.percentiles.p90-1hour]
  flushIntervalSeconds = 60
  percentile = 90
    
  [calc.percentiles.p50-1hour]
  flushIntervalSeconds = 60
  percentile = 50