# statsd.net configuration file.
# This is a TOML file. Read the spec here: https://github.com/mojombo/toml 

[general]
name = "foocollector"

[listeners]
  [listeners.udp]
  enabled = true
  port = 12000

  [listeners.http]
  enabled = false
  port = 12001

[backends]
  [backends.sqlserver]
  enabled = true
  connectionString = "server=gamingdb2;database=lvtest;uid=sa;password=!@#$%A1"
  
  [backends.graphite]
  enabled = true
  host = "metricsas1"
  port = 2003

  [backends.console]
  enabled = true

[calc]
flushIntervalSeconds = 10
gaugesNamespace = "stats.gauges"
countersNamespace = "stats_counts"
setsNamespace = "sets"
timersNamespace = "stats.timers"

  [calc.percentiles.p90_5min]
  flushIntervalSeconds = 300
  percentile = 90

  [calc.percentiles.p90_1hour]
  flushIntervalSeconds = 3600
  percentile = 90
    
  [calc.percentiles.p50_1hour]
  flushIntervalSeconds = 3600
  percentile = 50

[console]
  enabled = true
  localhostOnly = true
  port = 8080