# statsd.net configuration file.
# For help on configuring this file, please see https://github.com/lukevenediger/statsd.net/wiki/Statsd.net-Configuration-File

[general]
name = "statsd"

[listeners]
  [listeners.udp]
  enabled = true
  port = 12000

[backends]

  [backends.console]
  enabled = true

  [backends.librato]
  enabled = true
  email = "lukev@lukev.net"
  token = "10745d7756eb9ceb0f60425431ac770eb69005e733eae57ffaf172c1cf43876e"
  source = "unique-per-statsd-instance"
  retryDelaySeconds = 5
  postTimeoutSeconds = 30
  maxBatchSize = 10
  countersAsGauges = true

[calc]
flushIntervalSeconds = 10
gaugesNamespace = "gauges"
countersNamespace = "counts"
setsNamespace = "sets"
timersNamespace = "timers"
removeZeroGauges = false

  [calc.percentiles.p90-5min]
  flushIntervalSeconds = 30
  percentile = 90

  [calc.percentiles.p90-1hour]
  flushIntervalSeconds = 60
  percentile = 90
    
  [calc.percentiles.p50-1hour]
  flushIntervalSeconds = 60
  percentile = 50

[console]
enabled = true
localhostOnly = true
port = 8080
