# statsd.net configuration file.
# For help on configuring this file, please see https://github.com/lukevenediger/statsd.net/wiki/Statsd.net-Configuration-File

[general]
name = "statsd"

[listeners]
  [listeners.udp]
  enabled = true
  port = 12000

  [listeners.http]
  enabled = true
  port = 12001

[backends]
  [backends.sqlserver]
  enabled = false
  connectionString = "server=localhost;database=metrics;uid=mmetricsuser;password=metricsuser"
  writeBatchSize = 500
  
  [backends.graphite]
  enabled = true
  host = "graphite"
  port = 2003

  [backends.console]
  enabled = true

[calc]
flushIntervalSeconds = 10
gaugesNamespace = "gauges"
countersNamespace = "counts"
setsNamespace = "sets"
timersNamespace = "timers"

  [calc.percentiles.p90_5min]
  flushIntervalSeconds = 300
  percentile = 90

  [calc.percentiles.p90_1hour]
  flushIntervalSeconds = 3600
  percentile = 90
    
  [calc.percentiles.p50_1hour]
  flushIntervalSeconds = 3600
  percentile = 50

[console]
enabled = true
localhostOnly = true
port = 8080
