# statsd-relay service configuration file.
# For help on configuring this file, please see [missing]()

[general]
name = "statsd-relay"

[listeners]
  [listeners.udp]
  enabled = true
  port = 8000

  [listeners.tcp]
  enabled = false
  port = 8001

  [listeners.http]
  enabled = false
  port = 8002

[target]
host = "localhost"
port = 12000